language: haskell

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

sudo: required

cache:
  directories:
    - ~/rolandtritsch/haskell-aoc-2017/.stack-work
    - ~/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack build --dry-run

script:
  - travis_wait 60 ./bin/run.sh

env:
  - DAY=00 PART=1 TYPE=EXE
  - DAY=00 PART=2 TYPE=EXE
  - DAY=00 PART=1 TYPE=TEST
  - DAY=00 PART=2 TYPE=TEST
  - DAY=01 PART=1 TYPE=EXE
  - DAY=01 PART=2 TYPE=EXE
  - DAY=01 PART=1 TYPE=TEST
  - DAY=01 PART=2 TYPE=TEST
  - DAY=02 PART=1 TYPE=EXE
  - DAY=02 PART=2 TYPE=EXE
  - DAY=02 PART=1 TYPE=TEST
  - DAY=02 PART=2 TYPE=TEST
